-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.4.32-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para llibres
DROP DATABASE IF EXISTS `llibres`;
CREATE DATABASE IF NOT EXISTS `llibres` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `llibres`;

-- Volcando estructura para tabla llibres.llibres
DROP TABLE IF EXISTS `llibres`;
CREATE TABLE IF NOT EXISTS `llibres` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titol` varchar(255) NOT NULL,
  `imagen` varchar(255) NOT NULL,
  `sinopsis` text DEFAULT NULL,
  `autor` varchar(255) NOT NULL,
  `spicy` tinyint(1) NOT NULL DEFAULT 0,
  `ISBN` varchar(20) DEFAULT NULL,
  `estat` tinyint(1) NOT NULL,
  `prioritat` tinyint(1) NOT NULL,
  `data_inici` date DEFAULT NULL,
  `data_fi` date DEFAULT NULL,
  `comprat` tinyint(4) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla llibres.llibres: ~47 rows (aproximadamente)
INSERT INTO `llibres` (`id`, `titol`, `imagen`, `sinopsis`, `autor`, `spicy`, `ISBN`, `estat`, `prioritat`, `data_inici`, `data_fi`, `comprat`, `created_at`, `updated_at`, `deleted_at`) VALUES
	(1, 'Todas mis heridas', 'https://imagessl6.casadellibro.com/a/l/s7/16/9788490436516.webp', 'Una historia increíblemente emotiva sobre el significado de crecer y seguir adelante cuando tu cuerpo es tu mayor enemigo. Un retrato conmovedor de una chica en un mundo que no le debe nada y que, sin embargo, tanto le ha quitado.\r\n\r\nCharlie está deshecha. Con solo diecisiete años, ha perdido ya mucho más de lo que la mayoría de las personas llega a perder en toda su vida. Mientras el resto de las chicas de su edad solo se preocupan por banalidades, Charlie ha tenido que madurar repentinamente y aprender a olvidar. Pero olvidar no es fácil, y ella solo sabe hacerlo autolesionándose. Cada nueva herida, golpe o corte la ayudarán a borrar de su mente lo que pasó con su padre, su mejor amiga y su madre.\r\n\r\nY cuando Charlie se ve obligada a abandonar el centro de rehabilitación en el que lucha por sobrevivir, se encuentra sola en un viaje inimaginable, un largo trayecto que ha de permitirle curar todas sus heridas.', 'Kathleen Glasgow', 0, '9788490436516', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:14:41', '2025-12-29 09:17:35', NULL),
	(2, 'Nosotros en la luna', 'https://imagessl0.casadellibro.com/a/l/s7/90/9788408223290.webp', 'Una historia sobre el amor, el destino y la búsqueda de uno mismo.\r\n\r\nNo hay nada más eterno que un encuentro fugaz.\r\n\r\n\r\nUna noche en París. Dos caminos entrelazándose.\r\n\r\n\r\nCuando Rhys y Ginger se conocen en las calles de la ciudad de la luz, no imaginan que sus vidas se unirán para siempre, a pesar de la distancia y de que no puedan ser más diferentes. Ella vive en Londres y a veces se siente tan perdida que se ha olvidado hasta de sus propios sueños. Él es incapaz de quedarse quieto en ningún lugar y cree saber quién es. Y cada noche su amistad crece entre e-mails llenos de confidencias, dudas e inquietudes. Pero ¿qué ocurre cuando el paso del tiempo pone a prueba su relación?\r\n\r\n\r\n¿Es posible colgarse de la luna junto a otra persona sin poner en riesgo el corazón?', 'Alice Kellen', 0, '9788408223290', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:15:13', '2025-12-29 09:20:47', NULL),
	(3, 'Te espero en el fin del mundo', 'https://imagessl7.casadellibro.com/a/l/s7/37/9788408270737.webp', 'Emociónate con la historia de Vi y Levi, un amor que tendrá que luchar contra la distancia y el peso de los sueños.\r\n\r\n¿Con quién te gustaría estar si supieras que mañana se acaba el mundo?\r\n\r\nViolet y Levi se conocen desde niños.\r\nÉl sueña con crear un hogar.\r\nElla, con escapar del suyo.\r\nSon mejores amigos, siempre están el uno para el otro y, cuando empiezan a crecer, se dan cuenta de que sus sentimientos también lo hacen.\r\nIntensos. Imparables. Únicos.\r\nPero Levi desea echar raíces entre montañas mientras que Violet quiere volar muy alto y comerse el mundo.\r\nEs posible que no existan dos personas más incompatibles que encajen mejor.\r\nUna cabaña abandonada, una colección de figuras de madera y un amor de los que marcan toda una vida.\r\nEl de Levi, el chico que hacía muchas preguntas, y el de Vi, la chica que tenía todas las respuestas.', 'Andrea Longarela', 0, '9788408270737', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:16:17', '2025-12-29 09:21:17', NULL),
	(4, 'Un beso en paris', 'https://imagessl2.casadellibro.com/a/l/s7/72/9788424668372.webp', 'La torre Eiffel, Amélie y un montón de reyes que se llaman Luis. Esto es todo lo que Anna conoce de Francia. Por eso, cuando sus padres le anuncian que pasará un año en un internado de París, la idea no acaba de convencerla. Pero, en la Ciudad del Amor, conoce al chico ideal: Étienne St. Clair. Es listo, encantador y muy guapo. El único problema es que también tiene novia. ¿Conseguirá Anna el ansiado beso de su príncipe azul?', 'Stephanie Perkins', 0, '9788424668372', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:16:44', '2025-12-29 09:21:43', NULL),
	(5, 'A dos metros de ti', 'https://imagessl5.casadellibro.com/a/l/s7/25/9788417605025.webp', 'El libro de la conmovedora película con ColeSprouse yHaley Lu Richardson\r\n\r\nNecesitamos estar cerca de las personas que queremos casi tanto como el aire que respiramos.\r\n\r\nA Stella Grant le gusta tener el control, a pesar de no poder dominar sus propios pulmones, que la han tenido en el hospital la mayor parte de su vida. Por encima de todo, Stella necesita controlar su espacio para mantenerse alejada de cualquier persona o cosa que pueda transmitirle una infección y poner en peligro su trasplante de pulmón. Dos metros de distancia. Sin excepciones.\r\n\r\nEn cuanto a Will Newman, lo único que quiere controlar es cómo salir de este hospital. No le importan sus tratamientos, o si hay una nueva medicación en ensayo clínico. Pronto cumplirá dieciocho años y podrá desconectar todas estas máquinas. Desea ir a ver el mundo, no solo sus hospitales.\r\n\r\nWill y Stella no pueden acercarse. Solo con que respiren cerca, Will podría provocar que Stella perdiera su puesto en la lista de trasplantes. La única forma de mantenerse con vida es mantenerse alejados.', 'Rachael Lippincott', 0, '9788417605025', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:17:10', '2025-12-29 09:22:29', NULL),
	(6, 'Prohibido creer en historias de amor', 'https://imagessl7.casadellibro.com/a/l/s7/97/9788490437797.webp', 'Prohibido creer en historias de amor, la nueva novela de Javier Ruescas, es una comedia romántica sobre amistad, aventuras y amor en los tiempos de YouTube.\r\n\r\nCuando tienes 17 años y toda tu vida pasa en YouTube, llega un momento en el que ya no sabes quién eres. Eso es precisamente lo que le sucede a Cali: su familia tiene un canal con dos millones de seguidores y su novio es el youtuber más conocido del momento.\r\n\r\nPor su parte, Héctor vive en una residencia de menores y lucha por averiguar de dónde proviene. Pero el único recuerdo que conserva de su pasado es una cinta de casete con una canción que toca siempre en el metro con la esperanza de que algún día alguien la escuche y la reconozca.\r\n\r\nY ahí es donde se cruzan sus miradas.\r\n\r\nLas vidas de ambos quedarán entrelazadas para siempre cuando descubran el origen de la canción, el póster de una película olvidada y un cine abandonado lleno de secretos... Todo sin romper la única norma que Héctor sigue a rajatabla: está prohibido creer en el amor.', 'Javier Ruescas', 0, '9788490437797', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:17:44', '2025-12-29 09:22:46', NULL),
	(7, 'Hasta que nos quedemos sin estrellas', 'https://imagessl1.casadellibro.com/a/l/s7/21/9788408267621.webp', '«No tengo ni idea de lo que es el amor. Creo que nunca antes lo había sentido. Lo único que tengo claro es que, cada vez que pienso en eso, eres tú quien se me viene a la cabeza»\r\n\r\n\r\nMaia. Liam.\r\n\r\n\r\nLa historia de cómo dos astros colisionan\r\n\r\n\r\nLiam ha perdido su pasión por YouTube. Está metido en una relación falsa que ha tenido un resultado catastrófico: se ha enamorado de la chica, Michelle, y ahora ella sale a escondidas con su mejor amigo.\r\n\r\n\r\nMaia tiene pesadillas desde la noche del accidente. Todos los días va al hospital a visitar a una estrella cuya luz se tambalea.\r\n\r\n\r\nUn cumpleaños caótico. Una botella de vodka y un youtuber borracho que acaba durmiendo en el coche de una desconocida.\r\n\r\n\r\n¿Qué mejor combinación para conseguir que dos astros colisionen?', 'Inma Rubiales', 0, '9788408252962', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:18:09', '2025-12-29 09:23:35', NULL),
	(8, 'El arte de ser nosotros', 'https://imagessl8.casadellibro.com/a/l/s7/28/9788408267928.webp', 'La vida no es justa, y eso Logan lo sabe muy bien. Después de una dolorosa pérdida, su corazón se ha vuelto hermético, frío e inquebrantable. Por eso no le importa que todos crean que es el malo de la historia.\r\n\r\n\r\nLeah nunca se ha sentido la protagonista de la suya. Vive con la cabeza enterrada en los libros, intentando pasar desapercibida, y se refugia en la gran comunidad de lectores que tiene en internet.\r\n\r\n\r\nLeah no es el tipo de chica que Logan está buscando.\r\n\r\n\r\nY Logan es la clase de chico que Leah trata de evitar.\r\n\r\n\r\nQuizá por eso lo que hay entre ellos funciona tan bien.\r\n\r\n', 'Inma Rubiales', 0, '9788408267928', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:18:40', '2025-12-29 09:24:17', NULL),
	(9, 'El tiempo que tuvimos', 'https://imagessl4.casadellibro.com/a/l/s7/34/9788419357434.webp', 'Liam y Grace: una historia de amor y recuerdos imposible de olvidar. Un nuevo e imprescindible standalone de la mano de Cherry Chic.\r\n\r\nLiam OCallaghan y Grace Fitzgerald siempre han estado en la vida del otro.\r\n\r\nDesde pequeños han estado unidos por una promesa: la de reunirse cada dos años para firmar un contrato que los señala como mejores amigos y enterrarlo de nuevo dentro de una cajita bajo el Árbol de las Hadas.\r\n\r\nNada podía romper la tradición, del mismo modo que nada podía separarlos a ellos.\r\n\r\nHasta que un día todo cambia.\r\n\r\nEsta es la historia de dos personas que se quisieron tanto y de tantas formas que, en algún punto de sus vidas, no supieron qué hacer con tanto amor.', 'Cherry Chic', 0, '9788419357434', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:19:07', '2025-12-29 09:24:37', NULL),
	(10, 'Cuando seamos sueños de papel', 'https://imagessl9.casadellibro.com/a/l/s7/79/9788408283379.webp', '¿Y si el amor de tu vida está más cerca de lo que crees?\r\n\r\nKei está desesperado. Se ha comprometido a trabajar en una parada de Sant Jordi con su madre. Odia los libros; para él solo son un montón de hojas de papel sin ningún sentido.\r\n\r\nAidé sigue creyendo en aquellos sueños de papel de los que le habló su abuela. Le encanta perderse entre los puestos repletos de libros en un día tan especial para Barcelona, pero lo último que espera es encontrarse con un italiano engreído que vuelve a despertarle sentimientos enterrados en su piel.\r\n\r\nKei y Aidé no están dispuestos a entenderse, pero el destino hará de las suyas y convertirá su historia en la más bonita de Sant Jordi.', 'Pol Ibáñez', 0, '9788408283379', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:20:05', '2025-12-29 09:24:54', NULL),
	(11, 'Las luces de febrero', 'https://imagessl5.casadellibro.com/a/l/s7/35/9788419421135.webp', 'Ellie Ross vive por y para el baloncesto.\r\n\r\n¿Su objetivo? Ser la primera chica en el equipo de su ciudad.\r\n\r\n¿Su mayor obstáculo? Víctor, con quien no habla desde los quince años y con quien, desde luego, no terminó nada bien.\r\n\r\nJay Ross vive por y para su familia.\r\n\r\n¿Su objetivo? Encontrar cuál es su propósito de una vez por todas.\r\n\r\n¿Su mayor obstáculo? El nuevo cuidador de su abuela: el despreocupado y odiosamente perfecto Nolan.\r\n\r\nDel amor al odio hay solo un paso, pero del odio al amor hay un camino muy largo. Uno lleno de crisis existenciales y pelotazos en la cabeza.\r\n\r\nY, como cada año, las luces de febrero aguardan al final del camino. ¿Has pensado ya en tu deseo?\r\n\r\nLa suerte está echada.', 'Joana Marcús', 0, '9788419421142', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:20:40', '2025-12-29 09:25:13', NULL),
	(12, 'Todo este tiempo', 'https://imagessl8.casadellibro.com/a/l/s7/98/9788417605698.webp', 'Una emocionante novela de Rachael Lippincott, la autora del best seller A dos metros de ti.\r\n\r\n¿Es posible encontrar el amor después de perderlo todo?\r\n\r\nUna intensa y reveladora historia de amor que te hará creer en el destino.\r\n\r\nKyle y Kimberly eran la pareja perfecta desde el instituto. Pero la noche de su graduación tienen un accidente de coche y Kimberly muere. La vida de Kyle cambia para siempre y no parece que nadie pueda entender cómo se siente. Hasta que llega Marley.\r\n\r\nElla también está pasando por una situación similar y, cuando conoce a Kyle, todas sus emociones secretas y nunca dichas conectan inmediatamente. Ambos han encontrado en el otro la respuesta a su dolor, pero algo está a punto de ocurrir que hará que sus vidas estallen de la forma más insospechada.', 'Rachael Lippincott', 0, '9788417605698', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:21:01', '2025-12-29 09:25:38', NULL),
	(13, 'Todo lo que nunca fuimos', 'https://imagessl1.casadellibro.com/a/l/s7/51/9788408221951.webp', 'Leah está rota. Leah ya no pinta. Leah es un espejismo desde el accidente que se llevó a sus padres.\r\n\r\nAxel es el mejor amigo de su hermano mayor y, cuando accede a acogerla en su casa durante unos meses, quiere ayudarla a encontrar y unir los pedazos de la chica llena de color que un día fue. Pero no sabe que ella siempre ha estado enamorada de él, a pesar de que sean casi familia, ni de que toda su vida está a punto de cambiar.\r\n\r\nPorque ella está prohibida, pero le despierta la piel.\r\n\r\nPorque es el mar, noches estrelladas y vinilos de los Beatles.\r\n\r\nPorque a veces basta un «deja que ocurra» para tenerlo todo.', 'Alice Kellen', 0, '9788408298625', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:21:26', '2025-12-29 09:26:48', NULL),
	(14, 'Experimento de amor en Nueva York', 'https://imagessl7.casadellibro.com/a/l/s7/47/9788412622447.webp', 'Rosie está desesperada. Solo tiene ocho semanas para escribir una novela romántica en medio de un horrible bloqueo creativo. Y además se le ha caído el techo encima, literalmente. Por suerte, puede refugiarse en el piso de Lina mientras ella está de viaje. Lo que Rosie no sabe es que Lucas, el primo de su mejor amiga y a quien ha estado acechando por Instagram, también se quedará allí. Lucas es una alma libre con abdominales de acero, sonrisa de ensueño, dotes de cocina y un par de secretos. Pero el plato fuerte es que le propone a Rosie un experimento que despertará mucho más que su inspiración.', 'Elena Armas', 0, '9788412622447', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:22:43', '2025-12-29 09:27:12', NULL),
	(15, 'Todo lo que somos juntos', 'https://imagessl8.casadellibro.com/a/l/s7/68/9788408221968.webp', 'El desenlace de la bilogía «Deja que ocurra». ¿Qué pasará con Axel y Leah?\r\n\r\nHan pasado tres años desde la última vez que Axel y Leah se vieron.\r\n\r\n\r\nAhora, Leah está a punto de cumplir su sueño de exponer en una galería.\r\n\r\n\r\nY, pese al pasado, Axel necesita formar parte de un momento como ese.', 'Alice Kellen', 0, '9788408298632', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:23:18', '2025-12-29 09:27:48', NULL),
	(16, 'El día que dejó de nevar en Alaska', 'https://imagessl4.casadellibro.com/a/l/s7/64/9788417421564.webp', 'El día que dejó de nevar en Alaska\r\n\r\nMás de 150.000 ejemplares vendidos en español.\r\n\r\nAutora sensación de TikTok. Más de 350 millones de visualizaciones en BookTok.\r\n\r\nNo te pierdas una de las novelas más importantes del género romántico de los últimos tiempos.\r\n\r\nUn chico con el corazón de hielo\r\n\r\nUna chica que huye de sí misma\r\n\r\nDos destinos que se cruzan', 'Alice Kellen', 0, '9788417421564', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:23:43', '2025-12-29 09:28:40', NULL),
	(17, 'El chico de arriba', 'https://imagessl7.casadellibro.com/a/l/s7/87/9788419241887.webp', 'Enamorarse no estaba en los planes de Ruby Graham, hasta que conoció a Kem Woods... ¡Déjate enamorar por la comedia romántica con más giros y curvas de los últimos tiempos!\r\n\r\nCuando menos te lo esperas, el destino se muda al piso de arriba\r\n\r\nRuby Graham tiene dos pasatiempos favoritos: la lectura y salir con su mejor amiga, Amber. Las dos chicas son polos opuestos, pero en eso radica su amistad. Bueno, en eso y en que Amber es la única otra adolescente de su edad en el edificio.\r\n\r\nHasta que llegan los Woods.\r\n\r\nEl entusiasmo y la curiosidad de Ruby por sus nuevos vecinos se disipa de golpe cuando Kem Woods, el hijo mayor, arruina uno de sus preciados libros al tirarle encima un cubo de agua. Enfurecida, Ruby se promete a sí misma odiarlo por toda la eternidad.\r\n\r\nPero no es tan fácil odiar a Kem, y cuando el amor llama a la puerta de Ruby, también lo hacen los celos, las mentiras, las traiciones y los secretos.\r\n\r\nAhora, Ruby deberá decidir entre la verdadera amistad o el verdadero amor.', 'Marie Jenn', 0, '9788419241894', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:25:21', '2025-12-29 09:29:01', NULL),
	(18, 'Romper el hielo', 'https://imagessl3.casadellibro.com/a/l/s7/78/9788466674478.webp', 'El fenómeno viral de TikTok que derrite el hielo. Un rivals to lovers que ha conquistado la lista de más vendidos de The New York Times.\r\n\r\nLas chispas saltan cuando una patinadora artística y el capitán del equipo de hockey se ven obligados a compartir pista y a acercarse mucho más de lo que querrían.\r\n\r\nAnastasia Allen está decidida a entrar en el equipo olímpico de patinaje artístico de Estados Unidos y, cuando consigue una beca para la Universidad de California, todo parece ir de acuerdo con su plan.\r\n\r\nEl objetivo de Nathan Hawkins como capitán del equipo de hockey es mantener a sus chicos sobre el hielo cueste lo que cueste, pero todo se complica cuando tienen que compartir pista con una patinadora guapísima y con muy mal genio.\r\n\r\nLa situación obliga a estos rivales a pasar tiempo juntos, pero Anastasia está tranquila. Sabe perfectamente que un jugador de hockey jamás podría distraerla, y mucho menos Nate... ¿verdad?', 'Hannah Grace', 5, '9788466674478', 1, 0, '2025-05-24', '2025-05-24', 1, '2025-05-24 19:25:50', '2025-12-29 09:29:42', NULL),
	(19, 'Todos los lugares que mantuvimos en secreto', 'https://imagessl1.casadellibro.com/a/l/s7/61/9788408283461.webp', 'Inma Rubiales vuelve a enamorarnos con esta novela que ha triunfado en Wattpad.\r\n\r\nMaeve no sabe mucho sobre sí misma. Solo que no deja de pensar en si su madre cumplió todos sus sueños antes de morir, que la relación con su novio va cada vez peor y que está cansada de que todos sus días sean iguales.\r\n\r\n\r\nCuando, por un impulso, acaba comprando un billete solo de ida a la otra parte del mundo para volver al pueblo en el que vivió cuando era niña, lo que menos esperaba era reencontrarse allí con el que fue su mejor amigo de la infancia.\r\n\r\n\r\nConnor siempre supo que tarde o temprano Maeve regresaría. Lo que nunca pensó es que fuera a ser así.\r\n\r\n\r\nTan caótica. Tan perdida. Como si aún estuviera por definir.\r\n\r\n\r\nSi el miedo de ambos es desperdiciar sus vidas sin haber hecho nada que merezca la pena, ¿qué mejor que escribir una lista con todo lo que quieren hacer antes de morir y cumplirla juntos?', 'Inma Rubiales', 0, '9788408297666', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:26:05', '2025-12-29 09:30:09', NULL),
	(20, 'Kiss & Cry', 'https://imagessl2.casadellibro.com/a/l/s7/02/9788424666002.webp', 'En la pista de la vida, los patines los llevas tú.\r\n\r\nVeronica Leckie y Brooks Marten son las ovejas negras del patinaje sobre hielo. Tras quedar fuera del podio por los pelos en los Mundiales Júnior, ha llegado la hora de que pasen a la categoría Senior justo a tiempo para los Juegos Olímpicos. El bicampeón olímpico Nikita Ogorodnikov se ofrece a entrenarlos y se mudarán a Toronto, donde Veronica compartirá pista con su polo opuesto: la seria jugadora de hockey Frankie Kelleher. ¿Podrán soportar la presión? Un gran reto requiere de un gran esfuerzo y sólo ellos podrán decidir su destino.', 'Andrea Tomé', 0, '9788424666002', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:26:24', '2025-12-29 09:30:33', NULL),
	(21, 'Las estrellas en tus ojos', 'https://imagessl1.casadellibro.com/a/l/s7/51/9788492918751.webp', 'En esta comedia romántica de la autora de¿Álex, quizás?, la corriente vida de una adolescente se sale de la ruta establecida cuando se queda atrapada en medio del bosque con su peor enemigo: el chico que le rompió el corazón.\r\n\r\nDesde el baile de bienvenida del año pasado, Zorie y Lennon -mejores amigos ahora convertidos en peores enemigos-, han estado evitándose el uno al otro hasta hacer de ello una forma de arte. No les molesta que sus familias sean la versión moderna de los Montesco y los Capuleto.\r\n\r\nPero cuando un viaje de acampada en grupo no sale como habían previsto, Zorie y Lennon se quedan aislados en medio del bosque. Solos. Y juntos. ¿Qué podría salir mal?\r\n\r\nCon la única compañía del otro, Zorie y Lennon no tienen otra opción que tratar de saldar sus cuentas pendientes entre punzadas de ingenio y algún que otro ataque verbal. Pero discutir al mismo tiempo que luchan contra las fuerzas de la naturaleza hace que salir ilesos del bosque sea cada vez menos probable.\r\n\r\nY mientras los dos se adentran en las profundidades de un paisaje rural, salen a la superficie secretos y sentimientos ocultos. Pero ¿podrá la renovada conexión entre Zorie y Lennon sobrevivir en el mundo real? ¿O solo fue un espejismo fruto del aire fresco del bosque y la magia de las estrellas?', 'Jenn Bennett', 0, '9788492918751', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:28:42', '2025-12-29 09:30:58', NULL),
	(22, 'Hija de la tierra', 'https://imagessl2.casadellibro.com/a/l/s7/02/9788419507402.webp', '¡Descubre la nueva trilogía de fantasía romántica de Andrea Longarela!\r\n\r\nZiara vive en la Casa Verde y es una de las Novias del Nuevo Mundo, la esperanza de los últimos hombres.\r\n\r\nAún no ha sucedido, pero un día soñará con el hombre destinado a ella y cruzará los muros de su hogar para adentrarse en terreno desconocido:\r\n\r\nEn ese mundo del que la han protegido y que tanto ansía conocer.\r\n\r\nUn encuentro inesperado en el Bosque Sagrado, una unión entre dos personas que se ven obligadas a compartir camino y un secreto revelado harán que la vida de Ziara cambie para siempre.\r\n\r\n¿Estás preparado para adentrarte en el reino de Cathalian?', 'Andrea Longarela', 0, '9788419507402', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:29:10', '2025-12-29 09:31:15', NULL),
	(23, 'La tormenta en un verano infinito', 'https://imagessl2.casadellibro.com/a/l/s7/12/9788418883712.webp', 'Las vidas de Aston y Madison cambiaron irremediablemente cuando tuvieron que separarse, cinco años atrás. Durante ese tiempo, cada uno ha tenido que enfrentarse a sus propios demonios, intentar curar sus heridas y aprender a sobrevivir sin el otro. Ella aún se acuerda de él, aunque es la culpable de que perdieran el contacto. Él aún le guarda rencor, aunque no ha dejado de echarla de menos ni un solo segundo. Cuando Madison vuelve a Santa Mónica para cursar el último año de instituto y se encuentra con un Aston tan irresistible como borde, entre ellos saltan chispas capaces de desencadenar una tormenta.\r\nSe quieren tanto como se odian. Y, en medio de todo ese caos, ambos guardan muchos secretos que no piensan revelar. ¿Qué ocurrirá cuando la verdad salga a la luz?', 'Raquel Attard', 0, '9788418883712', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:29:33', '2025-12-29 09:31:32', NULL),
	(24, 'Prohibido enamorarse', 'https://imagessl4.casadellibro.com/a/l/s7/24/9788410425224.webp', 'Hacer un trato con un chico malo nunca sentó tan bien\r\n\r\nHannah Wells ha encontrado por fin un chico que le gusta, pero se siente insegura en la seducción y el sexo. Si quiere conseguir que el chico que le interesa le preste atención, va a tener que salir de su zona de confort… Incluso si eso significa ser la tutora de Garrett Graham, el insoportable y arrogante capitán del equipo de hockey, a cambio de que finja salir con ella para así dejar de ser la chica invisible de la universidad.\r\n\r\nGarrett, por su parte, sueña con ser jugador de hockey profesional, pero sus malas notas ponen en peligro su futuro. Ese es el único motivo por el que accede a ayudar a Hannah a poner celoso a otro. Pero cuando un beso inesperado conduce al sexo más salvaje de su vida, a Garrett le queda claro que no le basta con fingir. El problema ahora es que tiene que conseguir que Hannah se enamore de él.', 'Elle Kennedy', 0, '9788418509681', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:30:05', '2025-12-29 09:31:57', NULL),
	(25, 'Objetivo tú y yo', 'https://imagessl1.casadellibro.com/a/l/s7/31/9788410425231.webp', 'Un error inocente podría separarlos para siempre\r\n\r\nJohn Logan es uno de los chicos más populares de la universidad. Es la estrella del equipo de hockey y puede conquistar a cualquier chica. Pero detrás de su sonrisa deslumbrante y de su actitud de chico seguro de sí mismo se esconde la tristeza por la vida que le espera después de la universidad: un callejón sin salida que lo alejará del deporte para siempre.\r\n\r\nUn encuentro inesperado y sexy con Grace Ivers, una estudiante de primero, es la distracción perfecta para no pensar en el futuro, pero cuando un error banal hace saltar por los aires la relación que estaban construyendo, Logan decide que pasará el último año de universidad haciendo cualquier cosa para que Grace le dé una segunda oportunidad. Esta vez, sin embargo, las reglas las dictará ella… y no piensa ponérselo fácil.\r\n\r\nBest seller del New York Times, no te pierdas la serie adictiva', 'Elle Kennedy', 0, '9788418509704', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:30:29', '2025-12-29 09:32:18', NULL),
	(26, 'Hijos de la magia', 'https://imagessl1.casadellibro.com/a/l/s7/01/9788419688101.webp', '¡Descubre la nueva trilogía de fantasía romántica de Andrea Longarela!\r\n\r\nLo que ha descubierto Ziara sobre sí misma lo cambia todo.\r\n\r\nAhora que es consciente de su poder, mil preguntas laatormentan cada segundo. ¿Quién es? ¿Cuál es su lugar? ¿Merecía la pena dejar aRedka atrás y sacrificar su futuro juntos?\r\n\r\nRedka nunca había tenido dudas... hasta ahora. Ziara hacambiado su mundo, y su huida lo ha colocado entre la espada y la pared. Tendrá que tomar una decisión crucial: ¿le debe lealtad al rey o a su corazón?\r\n\r\nMientras buscan respuestas y lidian con las secuelas de un amor aparentemente imposible, nuevos peligros y secretos amenazarán sus vidas y las de sus aliados, y pondrán en jaque el futuro del reino.\r\n\r\n¿Está en sus manos el destino de Cathalian?', 'Andrea Longarela', 0, '9788419688101', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:31:06', '2025-12-29 09:32:34', NULL),
	(27, 'Hijas del nuevo mundo', 'https://imagessl6.casadellibro.com/a/l/s7/86/9788419688286.webp', 'Llega el increíble final de la trilogía de fantasía romántica de Andrea Longarela!\r\n\r\nLo último que Ziara esperaba averiguar en Lithae es que el futuro de Cathalian está en sus manos. Menos aún descubrir el lazo que la une a su mayor enemigo.\r\n\r\nEl tiempo se agota y la guerra se avecina, pero sabe que mientras la sombra del rey Dowen se cierna sobre el reino, no habrá libertad posible en Cathalian.\r\n\r\nZiara se esforzará por cumplir su misión y hacer justicia. En su lucha, contará con la ayuda de nuevos e inesperados aliados y, por supuesto, con el amor y apoyo de Redka, aunque puede que el destino tenga planes desconocidos para él...\r\n\r\n¿Sacrificarías todo por la paz? ¿Incluso el amor?', 'Andrea Longarela', 0, '9788419688286', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:32:05', '2025-12-29 09:32:53', NULL),
	(28, 'Antes de diciembre', 'https://imagessl8.casadellibro.com/a/l/s7/48/9788418483448.webp', 'Una historia de amor y pasión con una cuenta atrás. Todo acabará Antes de diciembre.\r\n\r\nUna de las historias de amor más adictivas de Wattpad.\r\n\r\nPara Jenna Brown, su primer año en la Universidad suponía alejarse de su familia y sus amigos y enfrentarse al mundo por primera vez en su vida.\r\n\r\nSu novio le había dejado claras sus intenciones: a partir de ese momento, tenían una relación a distancia y abierta. Ambos podían hacer lo que quisieran porque sabían que se querían el uno al otro.\r\n\r\nAsí que no pasaba nada si no dejaba de acercarse al mejor amigo del novio de su compañera de habitación, ¿no?\r\n\r\nDe todos modos, ¿qué importaba si estaba con él en ausencia de su novio? Todo volvería a la normalidad en diciembre.', 'Joana Marcús', 0, '9788418949135', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:32:43', '2025-12-29 09:33:35', NULL),
	(29, 'Después de diciembre', 'https://imagessl7.casadellibro.com/a/l/s7/17/9788418798917.webp', 'odo cambiará... después de diciembre.\r\n\r\nEl tiempo es algo relativo.\r\n\r\nPara algunos pasa más rápido; para otros, no tanto.\r\n\r\nA Jenna Brown el último año se le ha hecho eterno.\r\n\r\nCuando superas una ruptura, el tiempo se rige por otras leyes físicas, y estar un año sin Jack Ross ha sido uno de los retos más difíciles de su vida. Pero ha conseguido superarlo, centrarse en sí misma y convertirse en una Jenna renovada que tiene un nuevo objetivo vital: terminar los estudios.\r\n\r\nAunque suponga volver al lugar donde todo empezó y que tantos recuerdos le evoca.\r\n\r\nAunque suponga tener que enfrentarse a las consecuencias de todas las decisiones que tomó un año atrás.\r\n\r\nJenna está convencida de que todo lo ocurrido antes de diciembre forma parte del pasado, pero... ¿qué ocurrirá después de diciembre?', 'Joana Marcús', 0, '9788418798917', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:33:16', '2025-12-29 09:34:09', NULL),
	(30, 'Tú y yo, invencibles', 'https://imagessl2.casadellibro.com/a/l/s7/22/9788408237822.webp', 'Lucas es familiar, impulsivo y transparente.\r\n\r\n\r\nJuliette es fuerte, introspectiva y liberal.\r\n\r\n\r\nÉl vive en Vallecas, trabaja en un taller de coches junto a su mejor amigo y por las tardes tocan en un grupo de música que marcará el curso de sus vidas para siempre.\r\n\r\n\r\nElla ha crecido con su abuela en un barrio acomodado, pero sueña con ser independiente, volar alto y dejar huella en el corazón de alguien.\r\n\r\n\r\nUna noche de 1978, en pleno estallido de la movida madrileña, sus caminos se cruzan. Entonces surge la atracción, el deseo, el amor. Un amor radiactivo que lo arrolla todo a su paso mientras los dos se vuelven inseparables en un ambiente desenfrenado lleno de cambios, atrapados entre el éxito y el fracaso, la luz y la oscuridad, el perdón y el orgullo.\r\n\r\n\r\nPero Lucas es imperfecto.\r\n\r\n\r\nY Juliette guarda secretos.\r\n\r\n\r\n¿Es eterna la pasión? ¿Se pueden olvidar la mentira y la traición sin que queden esquirlas?\r\n\r\n\r\n¿Qué ocurre cuando dos meteoritos que prometieron ser invencibles colisionan?\r\n\r\n\r\nSu amor es imperfecto, pero es su amor imperfecto', 'Alice Kellen', 0, '9788408237822', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:33:44', '2025-12-29 09:34:33', NULL),
	(31, 'Novia', 'https://imagessl8.casadellibro.com/a/l/s7/58/9791387739058.webp', 'Una peligrosa alianza entre una novia vampira y un licántropo alfa da lugar a una historia de amor tan intensa como para querer hincarle el diente\r\n\r\nMisery Lark, la única hija del consejero vampírico más poderoso del suroeste, es, de nuevo, una marginada. Los días de anonimato entre los humanos se le han acabado: su padre recurre a ella para poder llevar a cabo una alianza de paz histórica entre los vampiros y sus enemigos mortales, los licántropos, por lo que no le queda más remedio que resignarse al intercambio. Otra vez...\r\nLos licántropos son despiadados e impredecibles, y su alfa, Lowe Moreland, no es la excepción. Lidera a su manada con total autoridad, pero siempre de forma justa y, a diferencia del consejo vampírico, con compasión. Por el modo en que no pierde de vista a Misery, está claro que no se fía de ella. Y bien que hace...\r\nPorque Misery tiene sus motivos para haber accedido a ese matrimonio de conveniencia, motivos que nada tienen que ver con la política ni con ninguna alianza, sino con lo único que le ha importado en la vida. Y está dispuesta a hacer lo que haga falta para recuperar lo que ha perdido, incluso si para ello debe vivir a solas en territorio licántropo; a solas con el lobo.', 'Ali Hazelwood', 0, '9788419988126', 1, 0, '2025-05-26', '2025-05-28', 0, '2025-05-28 14:52:41', '2025-12-29 09:34:55', NULL),
	(32, 'El año en el que (casi) fuimos', 'https://imagessl0.casadellibro.com/a/l/s7/30/9788408282730.webp', '¿Hay que seguir apostando por el amor por muy inoportuno e inevitable que sea, o aceptar que algunas veces puede convertirse en un punto muerto entre lo que pudo ser y lo que nunca será?\r\n\r\nJosh siempre lo ha tenido todo fácil: es una persona que cae bien, con una novia maravillosa, un trabajo de paso y unos amigos que comparten sus gustos. Es feliz con poco, sin problemas.\r\n\r\nEntonces, conoce a Alessandra. Venida de Italia, llega para trabajar con él en el Madame Tussauds. Ella también tiene novio, amigos y una vida. Sin embargo, en cuanto congenian Josh sabe que ya no hay vuelta atrás.\r\n\r\nPorque de la amistad al amor hay un paso, y ellos no hacen más que bailar en esa línea fina que los separa.\r\n\r\nEso son problemas, errores y demasiados asuntos que Josh no sabe gestionar.\r\n\r\nPero si Less de verdad es su alma gemela, ¿está dispuesto a sacrificar la facilidad de su vida por tirarse al vacío?', 'Maria Zarate', 0, '9788408282730', 1, 0, '2025-05-29', '2025-06-02', 0, '2025-06-02 18:07:05', '2025-12-29 09:35:17', NULL),
	(33, 'Baile de luciérnagas', 'https://imagessl6.casadellibro.com/a/l/s7/36/9788417361136.webp', '"Alexandra Meynel acaba de llegar al internado de Macclesfield tras sobrevivir al accidente que se llevó a sus padres. Con el corazón anestesiado, en un ambiente en el que no termina de encajar y sin ganas de seguir adelante, encontrará en Albert, un alumno diferente al resto, la razón por la que seguir con vida. Sin embargo, pronto descubrirá que el Saint Cross es un lugar anclado en el pasado con un gran secreto entre sus paredes. Dos personas destinadas a estar juntas. Dos almas compañeras de viaje. Una promesa por cumplir."', 'Elena Castillo', 0, '9788417361136', 1, 0, '2025-06-02', '2025-06-14', 0, '2025-06-03 18:18:46', '2025-12-29 09:36:05', NULL),
	(34, 'Otra vez tú', 'https://imagessl9.casadellibro.com/a/l/s7/69/9788408244769.webp', '¿Existen las segundas oportunidades?\r\n\r\nUna boda frustrada. Un cálido reencuentro. Esta es la historia de Alex y Emma.\r\n\r\n\r\nJunto a sus dos mejores amigas, Emma deja atrás la ciudad de Nueva York y viaja a California con el firme propósito de pasar las vacaciones con un cóctel en la mano, bajo el sol, en las cálidas playas de la costa. Un plan perfecto. O al menos lo fue hasta que se encontró con Alex, el chico que no solo le rompió el corazón sino que, además, la dejó plantada una semana antes de subir al altar para darse el «sí, quiero».\r\n\r\n\r\nPor desgracia, Alex sigue siendo irresistible. Y, aunque Emma siente debilidad por su mirada azul y su sonrisa canalla, no está dispuesta a volver a caer en sus redes. Todo quedó atrás. Él quedó atrás. Así es como deben ser las cosas. El problema es que «querer» no siempre es suficiente y a veces hay recuerdos que pesan demasiado.\r\n\r\n\r\n«¿Existen las segundas oportunidades? Si eres de las que piensan que el amor no siempre es dos más dos, sino algo así como sesenta y tres por cuatro, divido entre ocho y multiplicado por infinito, tienes que conocer la historia de Alex y Emma».', 'Alice Kellen', 0, '9788408246039', 1, 0, '2025-06-14', '2025-06-16', 0, '2025-08-11 14:26:27', '2025-12-29 09:36:55', NULL),
	(35, 'Tal vez tú', 'https://imagessl1.casadellibro.com/a/l/s7/61/9788408245261.webp', 'Un futuro planificado. Un abogado seductor y canalla. ¿Conseguirá Elisa retomar las riendas de su vida?\r\n\r\nLa autora más vendida en edición de bolsillo en 2021 y 2022.\r\n\r\n\r\nTras un desengaño amoroso, Elisa está decidida a retomar las riendas de su vida e ir tachando propósitos de su lista: seguir siendo la mejor en su empleo, casarse, formar una familia… ¿El problema? Todavía no ha conocido al futuro padre de sus hijos. Pero ella tiene muy claro qué tipo de hombre anhela a su lado. Para empezar, uno que no se parezca en nada a Jack Helker, el abogado con el que ha de competir en su trabajo. A pesar de su sonrisa insolente y de ser el típico hombre que debería venir con un cartel de «no tocar», Elisa es incapaz de ignorar el deseo que siente cada vez que él está cerca.\r\n\r\n\r\n«Quizá la princesa no encuentre a un caballero a lomos de un corcel cuando se asome a la ventana de la torre, pero tal vez sí tropiece con un seductor chico de ojos grises el día que se atreva a dejar atrás los seguros muros del castillo.»', 'Alice Kellen', 0, '9788408308096', 1, 0, '2025-06-18', '2025-07-06', 0, '2025-08-11 14:27:28', '2025-12-29 09:37:23', NULL),
	(36, 'El efecto bola de nieve', 'https://imagessl0.casadellibro.com/a/l/s7/70/9788419467270.webp', 'Iris, tiene 19 años y está enamorada en secreto de su mejor amigo, Charles. Tras una estancia de seis meses en Estados Unidos, Charles regresa a Burdeos para pasar las fiestas. Iris está convencida de que la distancia le habrá ayudado a darse cuenta de que están hechos el uno para el otro. Pero Charles no está solo en el aeropuerto: le acompaña Jude, una vieja conocida de la familia. Su nueva novia. Las esperanzas de Iris se desmoronan al instante. Charles está enamorado de Jude, no de ella. Así que, antes de partir con él, como cada año, para celebrar la Navidad en los Pirineos con sus familias, Iris se deja convencer por una idea descabellada: ¿y si le pidiera a Alex, el hermano mayor de Charles que nunca ha sabido encontrar su sitio entre ellos, que se hiciera pasar por su novio? Aún más loco: ¿y si él aceptara seguirle el juego?', 'Clara Heraud', 0, '9788419467270', 1, 0, '2025-07-09', '2025-07-12', 0, '2025-08-11 14:28:57', '2025-12-29 09:37:41', NULL),
	(37, 'Quedará el amor', 'https://imagessl5.casadellibro.com/a/l/s7/75/9788408291275.webp', 'La gran novela de Alice Kellen.\r\nUn amor tan intenso y cálido como una tarde de verano\r\n\r\nEl sol baña los acantilados y las aguas turquesas del mar de Cornualles cuando Jane Bellamy y Cedric Stone se conocen en el verano de 1939. No están destinados a ser una ecuación perfecta, pero son jóvenes y el amor lo arrolla todo a su paso. Así que esta historia comienza como otras muchas: él y ella se enamoran. Hay primeras palabras, primeras miradas y primeros besos. Y luego la guerra, la nada. Solo oscuridad. Todo cambia.\r\n\r\n\r\nAños más tarde, en un hospital de Edimburgo, Margot Abbot sostiene en la mano un anillo que pertenece al paciente que dormita en la cama, Cedric Stone. Ella todavía no lo sabe, pero está a punto de abrir un baúl de recuerdos y descubrir qué ocurrió tras aquellos luminosos días de estío que quedaron atrás.', 'Alice Kellen', 0, '9788408305255', 1, 0, '2025-07-19', '2025-08-02', 0, '2025-08-11 14:29:51', '2025-12-29 09:37:58', NULL),
	(38, 'El color de las cosas invisibles', 'https://imagessl6.casadellibro.com/a/l/s7/96/9788408305996.webp', 'Un enemies-to-lovers que te hará creer en el amor.\r\n\r\nRain y Jack se odian. Rain y Jack pertenecen a planetas distintos. Rain y Jack no pueden tener menos cosas en común. Y, sin embargo, no dejan de cruzarse. Una y otra vez.\r\n\r\n\r\nPrimero en el instituto, luego en un concierto e, inesperadamente, también unos años después, cuando ya creían que no volverían a verse. Incluso se ven obligados a compartir una noche en una casa perdida en mitad del bosque.\r\n\r\n\r\nRain piensa que las casualidades no existen. Jack, que las causalidades no lo explican todo. Y los dos quieren tener la razón. Y los dos saben que se equivocan.\r\n\r\n\r\nY ambos intuyen que, sea como sea, cuando se trata de amor no hay teoría científica que haga entender el mecanismo de un corazón cuando otro lo sacude.', 'Andrea Longarela', 0, '9788408305996', 1, 0, '2025-08-02', '2025-08-10', 0, '2025-08-11 14:30:37', '2025-12-29 09:38:23', NULL),
	(39, 'El mapa de los anhelos', 'https://imagessl6.casadellibro.com/a/l/s7/56/9788408255956.webp', 'Una gran historia de amor llena de vida y esperanza.\r\n\r\nLa autora que ha enamorado a 2 millones de lectores.\r\n\r\n¿Y si te diesen un mapa para descubrir quién eres?\r\n\r\n¿Seguirías la ruta marcada hasta el final?\r\n\r\nImagina que estás destinada a salvar a tu hermana, pero al final ella muere y la razón de tu existencia se desvanece. Eso es lo que le ocurre a Grace Peterson, la chica que siempre se ha sentido invisible, la que nunca ha salido de Nebraska, la que colecciona palabras y ve pasar los días refugiada en la monotonía. Hasta que llega a sus manos el juego de El mapa de los anhelos y, siguiendo las instrucciones, lo primero que debe hacer es encontrar a alguien llamado Will Tucker, del que nunca ha oído hablar y que está a punto de embarcarse con ella en un viaje directo al corazón, lleno de vulnerabilidades y sueños olvidados, anhelos y afectos inesperados. Pero ¿es posible avanzar cuando los secretos comienzan a pesar demasiado? ¿Quién es quién en esta historia?', 'Alice Kellen', 0, '9788408255956', 1, 0, '2025-05-24', '2025-05-24', 0, '2025-05-24 19:25:44', '2025-12-29 09:39:00', NULL),
	(40, 'El faro de los amores dormidos', 'https://imagessl0.casadellibro.com/a/l/s7/30/9788408254430.webp', 'Este libro será tu próximo amor de verano\r\n\r\nVarela de Mar es un pueblo pequeño y tranquilo. Doscientos treinta y tres habitantes. Una playa que desaparece cuando sube la marea. Un faro abandonado.\r\n\r\nPor eso Alba no lo visita desde hace años. Bueno, por eso y porque allí fue donde aprendió lo que duele el amor, y la herida aún escuece.\r\n\r\nSin embargo, en Varela vive su abuelo, que ha comenzado a olvidar y que la necesita. También están los recuerdos que dejó en sus calles cuando se marchó sin mirar atrás. Y Enol, el chico de las conversaciones raras, la obsesión por las mareas y que parece haber nacido en la época equivocada.\r\n\r\nUn regreso inesperado, un faro lleno de secretos y dos historias inacabadas que, quizá, se merecen la oportunidad de un nuevo final.\r\n\r\n«Alba, vive el presente. Porque un día será pasado y te atormentará no haberte dado cuenta antes de que todo acaba, incluso lo que creías que era para siempre.»', 'Andrea Longarela', 0, '9788408254430', 1, 0, '2025-08-10', '2025-08-15', 0, '2025-08-21 13:48:26', '2025-12-29 09:39:26', NULL),
	(41, 'Nuestro lugar en el mundo', 'https://imagessl3.casadellibro.com/a/l/s7/73/9788408306573.webp', 'Luka recurre a la música para comprender sus pensamientos.\r\n\r\n\r\n\r\nNora la utiliza para huir de ellos.\r\n\r\n\r\n\r\nLuka no tiene muy claro cuál es su papel en el mundo. Ahora que ha salido del agujero que lo consumió el año pasado, está decidido a reconstruir su vida y arreglar todo lo que una vez rompió. Para ello, tendrá no solo que reconciliarse con su entorno, sino también consigo mismo, y desempolvar esos sueños que, hace ya un tiempo, dejó guardados en un cajón.\r\n\r\n\r\n\r\nNora posee un gran talento: mentir. Se le da genial hacer creer a sus padres que ha encontrado su hogar en Finlandia y que tiene un trabajo, un novio y una vida perfectos, como su hermana Margot. La realidad es que, debido a un reciente giro de los acontecimientos —que incluye a su mejor amigo, del que sigue enamorada, y a su nueva novia—, necesita encontrar a un nuevo compañero de piso de forma urgente.\r\n\r\n\r\n\r\nCuando, por caprichos del destino, Nora y Luka se ven obligados a convivir, el pasado sigue haciendo mella en ellos. No se llevan bien, pero pronto descubren que los dos se necesitan mutuamente, así que llegan a un acuerdo: Luka ayudará a Nora a mantener la farsa con su familia a cambio de que, cuando llegue el momento, ella le devuelva el favor. Total, fingir una relación tampoco tiene que ser tan difícil, ¿no?\r\n\r\n\r\n\r\nCon todas las cosas que los diferencian, ¿quién iba a decir que tendrían tantas otras en común?', 'Inma Rubiales', 4, '9788408306573', 1, 0, '2025-08-16', '2025-08-20', 0, '2025-08-21 13:49:49', '2025-12-29 09:40:40', NULL),
	(42, 'Saltan chispas', 'https://imagessl2.casadellibro.com/a/l/s7/22/9788466676922.webp', 'La serie de Maple Hills continúa después de Romper el hielo con dos monitores de campamento que se reencuentran tras un intenso lío de una noche.\r\n\r\nRuss Callaghan y Aurora Roberts coinciden en una fiesta de fin de curso y, después de dejarse llevar por un juego, acaban enrollándose. Sin embargo, Aurora se escabulle antes de que él tenga la oportunidad de preguntarle su nombre completo.\r\n\r\nSin saberlo, ambos van a trabajar en el mismo campamento de verano: Russ espera poner suficiente distancia con su padre, mientras que Aurora solo desea volver al último lugar donde se sintió como en casa.\r\n\r\nRuss sabe perfectamente que tiene prohibido «fraternizar» con Aurora si no quiere que lo echen. Desgraciadamente para él, a ella nunca le han importado mucho las reglas...\r\n\r\nAhora solo les queda descubrir si las chispas que saltaron entre ellos durante su primera noche quedarán en nada o si, por el contrario, lo incendiarán todo.\r\n\r\n', 'Hannah Grace', 3, '9788466676922', 1, 0, '2025-08-26', '2025-09-02', 0, '2025-11-05 10:03:57', '2025-12-29 09:42:05', NULL),
	(43, 'En las nubes', 'https://imagessl6.casadellibro.com/a/l/s7/86/9788410381186.webp', 'Después de Romper el hielo y Saltan chispas, llega la tercera novela de la serie Maple Hills, el fenómeno literario con el que Hannah Grace ha conquistado a millones de lectores.\r\n\r\nHenry deberá aliarse con Halle, una escritora encantadora, para que ambos consigan superar los retos que les depara el año universitario.\r\n\r\nHenry Turner se da cuenta de que va a tener que currárselo cuando acaba en una clase complicada con el profesor que menos le gusta. Encima, ahora es el nuevo capitán del equipo de hockey, así que no puede permitirse fallar. Pero todo cambia cuando se cuela en un club de lectura accidentalmente y conoce a Halle Jacobs.\r\n\r\nElla es una auténtica superestrella cuando se trata de hincar los codos. Aunque entre sus propias clases, el trabajo, el club de lectura y la novela que está intentando escribir no tiene tiempo para ser tutora de nadie, se ofrece a ayudar a Henry. Además, ¿no dicen que las nuevas experiencias ayudan a salir de los bloqueos creativos? Y él promete que va a darle muchas...\r\n\r\nLo único que tienen que hacer es ceñirse al reglamento que han establecido.\r\n\r\nAh, y no enamorarse, claro.', 'Hannah Grace', 1, '9788410381186', 1, 0, '2025-09-02', '2025-10-05', 0, '2025-11-05 10:06:01', '2025-12-29 09:42:33', NULL),
	(44, 'Rose in chains', 'https://imagessl1.casadellibro.com/a/l/s7/71/9788408307471.webp', 'Es hora de romper las cadenas. ¡Llega el próximo fenómeno de romantasy!\r\n\r\nLas fuerzas oscuras han vencido y el héroe destinado a salvarles ha muerto.\r\n\r\n\r\nLa guerra entre Eversun y Bomard ha terminado. Briony Rosewood, princesa de Eversun, es capturada, despojada de su magia y subastada en Bomard al mejor postor: Toven Hearst.\r\n\r\n\r\nA pesar de los horrores de su nueva realidad, la familia Hearst esconde secretos que hacen creer a Briony que no todo está perdido. ¿Y si su enemigo es su única esperanza?\r\n\r\n\r\nUna princesa en peligro. Una pasión que desafía las reglas. Una rebelión latente.', 'Julie Soto', 1, '9788408307471', 1, 0, '2025-11-07', '2025-12-08', 0, '2025-12-29 08:52:05', '2025-12-29 09:43:07', NULL),
	(45, 'Huyendo del vicio', 'https://imagessl7.casadellibro.com/a/l/s7/97/9788408273097.webp', 'Una novela ideal para combatir el calor: ligera, fresca y sumamente adictiva\r\n\r\nMARIA necesita escapar de su intensa vida dominada por el vicio, por lo que acepta una oferta de trabajo en un perdido pueblo, donde cree que logrará evadirse de las tentaciones que la rodean en la ciudad.\r\n\r\nLEONARDO busca un nuevo empleo y acude al pequeño pueblo del tío de su novia a trabajar en una granja.\r\n\r\nTRESPADEJO es ahora el destino de ambos, un remoto lugar en el que Maria y Leo, acompañados por sus nuevos y peculiares vecinos, vivirán una aventura llena de humor, deseo y… ¿amor?', 'Jon Azkueta Castro', 3, '9788408273097', 1, 0, '2025-12-08', '2025-12-14', 0, '2025-12-29 08:53:21', '2025-12-29 09:43:45', NULL),
	(46, 'Otra tonta historia de amor', 'https://imagessl9.casadellibro.com/a/l/s7/69/9788419131669.webp', 'Molly Marks se gana la vida como guionista de comedias románticas para Hollywood, y por eso tiene claro que el «amor» es un fraude. La única vez en su vida que fue tan inocente como para enamorarse fue cuando salió con su novio del instituto, Seth, al que no ha visto desde hace quince años.\r\n\r\nSeth Rubinstein cree en el amor, en ese grandioso que nos tiene reservado el destino, a pesar de ser uno de los abogados especializados en divorcios más famosos de Chicago. Durante la última década, ha buscado a esa persona especial en innumerables citas y relaciones fracasadas. Sabe que su alma gemela está en algún sitio… pero, de momento, nadie puede compararse a Molly Marks, la primera chica que le rompió el corazón.\r\n\r\nCuando los amigos de Molly la arrastran hasta Florida para asistir a la reunión de antiguos alumnos de su instituto, acaba santada al lado de Seth, como si los astros se hubieran confabulado. Después de demasiados Martinis, ambos deciden hacer una apuesta: quien consiga predecir el futuro de cinco parejas antes de la próxima reunión, tendrá que reconocer que el otro tenía razón sobre el amor. ¿La trampa? Ellos son la quinta pareja.\r\n\r\nMolly le asegura a Seth que la historia entre ellos no tiene remedio. Seth le promete que acabará irremediablemente enamorada de él. Ella cree que él está delirando, pero tiene cinco años para demostrarle que está equivocada.\r\n\r\nDivertida, sexy y llena de sentimiento, esta obra es perfecta para cualquier persona que crea en las almas gemelas, incluso en aquellas que se resisten a admitir que lo son.', 'Katelyn Doyle', 2, '9788419131669', 1, 0, '2025-12-14', '2025-12-24', 0, '2025-12-29 08:55:25', '2025-12-29 09:44:04', NULL),
	(47, 'La hipotesis del amor', 'https://imagessl2.casadellibro.com/a/l/s7/82/9788418945182.webp', 'Una relación falsa entre dos científicos se topa con la irresistible fuerza de la atracción.\r\n\r\nOlive Smith es una doctoranda de tercer año que no cree en las relaciones amorosas duraderas, pero su mejor amiga, Ahn, sí, y por eso Olive se ha metido en un lío monumental. A Ahn le gusta el exnovio de Olive, pero jamás daría el primer paso porque es una buena amiga. A Olive no le va a resultar nada fácil convencerla de que ha pasado página, puesto que los científicos necesitan pruebas. Por eso, como cualquier mujer con un mínimo de amor propio, se deja llevar por el pánico y besa al primer hombre con el que se encuentra para que Ahn la vea.\r\n\r\nEse hombre es nada más y nada menos que Adam Carlsen, un joven profesor tan reputado por la calidad de su trabajo como por su imbecilidad. Así que Olive se queda de piedra cuando Carlsen accede a mantener su farsa en secreto y ser su novio falso. Sin embargo, después de que un importante congreso científico se convierta en un desastre y Adam vuelva a sorprenderla con su apoyo inquebrantable (y sus inquebrantables abdominales), su pequeño experimento se acerca peligrosamente al punto de combustión. Olive no tarda en descubrir que la única cosa más complicada que una hipótesis sobre el amor es analizar su propio corazón bajo el microscopio.', 'Ali Hazelwood', 3, '9788418945182', 1, 0, '2025-12-24', '2025-12-28', 0, '2025-12-29 08:56:25', '2025-12-29 09:45:32', NULL);

-- Volcando estructura para tabla llibres.migrations
DROP TABLE IF EXISTS `migrations`;
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `version` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `group` varchar(255) NOT NULL,
  `namespace` varchar(255) NOT NULL,
  `time` int(11) NOT NULL,
  `batch` int(11) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla llibres.migrations: ~2 rows (aproximadamente)
INSERT INTO `migrations` (`id`, `version`, `class`, `group`, `namespace`, `time`, `batch`) VALUES
	(1, '2025-05-18-133434', 'App\\Database\\Migrations\\GeneresMigration', 'default', 'App', 1748114047, 1),
	(2, '2025-05-18-133436', 'App\\Database\\Migrations\\LlibresMigration', 'default', 'App', 1748114047, 1);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
